packages:
  - packages/**
  - template/vitepress-plugin-slot-inject-template
  - '!**/__test__/**'
  - '!**/demos/**'
  - '!**/packages/create-theme/**/template/**'
ignoredBuiltDependencies:
  - esbuild
