name: Auto Create Pull Request
on:
  push:
  # branches:
  #   - 'feature/*' # 监听以'feature/'开头的分支
  #   - 'fix/*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions: write-all
env:
  MAIN_BRANCH: ${{ vars.MAIN_BRANCH || 'master' }} # 主分支名称
jobs:
  create-pr:

    runs-on: ubuntu-latest
    steps:
      - name: github.env.MAIN_BRANCH
        run: echo "1 MAIN_BRANCH=${{ github.env.MAIN_BRANCH }}"
      - name: env.MAIN_BRANCH
        run: echo "2 MAIN_BRANCH=${{ env.MAIN_BRANCH }}"
      - name: printenv
        run: printenv

      - name: Checkout repository
        if: ${{ !contains(github.ref, env.MAIN_BRANCH)}}
        uses: actions/checkout@v4

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: auto-create-pr'
          title: '[AutoPR]${{ github.ref_name }}'
          body: |
            This is an automated pull request created from a feature branch.
            Please review and merge if ready.
          branch: ${{ github.ref }}
          base: ${{github.env.MAIN_BRANCH}} # 目标分支，根据你的仓库情况可能是'main'或'master'

      - name: Enable Pull Request Automerge
        if: steps.create_pr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
          merge-method: squash
