name: CreateReleaseTag

on:
  push:
    tags:
      - 'v*' # Push events to matching @sugarat/theme*
permissions: write-all
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Create Release for Tag
        id: release_tag
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          generateReleaseNotes: true
          draft: true
          body: |
            > Please refer to [CHANGELOG.md](https://github.com/ripplejourney/ripplejourney.github.io/blob/master/packages/theme/CHANGELOG.md) for details.
