name: CreateReleaseTag

on:
  push:
    tags:
      - 'v*' # Push events to matching @sugarat/theme*
permissions: write-all
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Create Release for Tag
        id: release_tag
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1.16.0
        with:
          generateReleaseNotes: true
          draft: true
          body: |
            > Please refer to [CHANGELOG.md](https://github.com/ripplejourney/ripplejourney.github.io/blob/master/packages/theme/CHANGELOG.md) for details.
